[package]
name = "perlxs_derive"
version = "0.2.0"
authors = ["perl-xs Authors"]
edition = "2021"
rust-version = "1.70"
description = "Derive macros for perl-xs"
license = "BSD-2-Clause"

[lib]
name = "perlxs_derive"
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full", "extra-traits"] }
quote = "1"
proc-macro2 = "1"
